### PR TITLE
Extra gui buttons for common usecases.

### PR DESCRIPTION
**Pull request by Wojbie**
Adds Copy To Clipboard buttons in valid spots + Adds buttons that link to text/code viewer ( on list page ) or target page ( on links page ).
Kinda makes sense to have those common functions simplified down to button click.

obraz
obraz
obraz

### CODE REVIEW

**Comment by Lemmmy** [comment]
super cool! perhaps move the new buttons into the same column as rename/delete on the list view?

**Comment by Wojbie** [comment]
I put them separate so on mobile you are less likely to press rename/delete when trying to copy link/open code view.

**Comment by Wojbie** [comment]
Hmm.. Now that i think about it there is a better way to layout those. Gimme a moment.

**Comment by Wojbie** [comment]
This looks better yes.
obraz
obraz

**Comment by Lemmmy** [comment]
you are wonderful!! just make sure the options button has the rounded corners on the right in the list view, not sure why it doesnt

**Comment by Wojbie** [comment]
Well i guess we will have to drop the group for now. Ready to merge.

**Comment by Lemmmy** [comment]
thanks a lot!!!

**Pull request merged**
